// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CiceroSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ciceroMeny() {
    driver.get("http://localhost:3000/no");
    driver.manage().window().setSize(new Dimension(1280, 752));
    driver.findElement(By.linkText("Om oss")).click();
    driver.findElement(By.linkText("Magasinet Klima")).click();
    driver.findElement(By.linkText("Tema")).click();
    driver.findElement(By.linkText("Ansatte")).click();
    driver.findElement(By.linkText("Prosjekter")).click();
    driver.findElement(By.linkText("Publikasjoner")).click();
    driver.findElement(By.linkText("Arrangementer")).click();
    driver.close();
  }
  @Test
  public void ciceroAnsatte() {
    driver.get("http://localhost:3000/no");
    driver.manage().window().setSize(new Dimension(1280, 752));
    driver.findElement(By.cssSelector(".styles_shortcutTile__pbJec:nth-child(2) .styles_title__vOtVv")).click();
    driver.findElement(By.cssSelector(".styles_searchBarWrapper__hx652 input")).click();
    driver.findElement(By.cssSelector(".styles_searchBarWrapper__hx652 input")).sendKeys("Kristin");
    driver.findElement(By.cssSelector(".styles_searchBarWrapper__hx652 .styles_submitBtn__sj98V")).click();
    driver.findElement(By.cssSelector(".styles_spacer-m__QzWXy:nth-child(2) h3")).click();
    driver.findElement(By.linkText("Om")).click();
    driver.close();
  }
  @Test
  public void ciceroProsjekter() {
    driver.get("http://localhost:3000/no");
    driver.manage().window().setSize(new Dimension(1280, 752));
    driver.findElement(By.cssSelector(".styles_shortcutTile__pbJec:nth-child(3) .styles_title__vOtVv")).click();
    driver.findElement(By.cssSelector(".styles_searchBarWrapper__hx652 input")).click();
    driver.findElement(By.cssSelector(".styles_searchBarWrapper__hx652 input")).sendKeys("Aviate");
    driver.findElement(By.cssSelector(".styles_searchBarWrapper__hx652 .styles_submitBtn__sj98V")).click();
    driver.findElement(By.cssSelector("h3")).click();
    driver.findElement(By.linkText("Bli med og forsk på kondensstriper!")).click();
    driver.findElement(By.cssSelector("h3")).click();
    driver.close();
  }
  @Test
  public void ciceroTema() {
    driver.get("http://localhost:3000/no");
    driver.manage().window().setSize(new Dimension(1280, 752));
    driver.findElement(By.cssSelector(".styles_shortcutTile__pbJec:nth-child(1) .styles_title__vOtVv")).click();
    driver.findElement(By.cssSelector(".styles_searchBarWrapper__hx652 input")).click();
    driver.findElement(By.cssSelector(".styles_searchBarWrapper__hx652 input")).sendKeys("Arealbruk");
    driver.findElement(By.cssSelector(".styles_searchBarWrapper__hx652 .styles_submitBtn__sj98V")).click();
    driver.findElement(By.cssSelector("h3")).click();
    driver.findElement(By.cssSelector(".styles_oneColumn__c8URn:nth-child(2) .styles_image__KrnLv h3")).click();
    driver.close();
  }
}
