// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CicerotestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ciceroMeny() {
    driver.get("https://cicero.oslo.no/no");
    driver.manage().window().setSize(new Dimension(1280, 752));
    driver.findElement(By.linkText("Vår ekspertise")).click();
    assertThat(driver.findElement(By.linkText("Vår ekspertise")).getText(), is("Vår ekspertise"));
    driver.findElement(By.linkText("Tjenester")).click();
    {
      WebElement element = driver.findElement(By.linkText("Tjenester"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Prosjekter")).click();
    driver.findElement(By.linkText("Publikasjoner")).click();
    driver.findElement(By.linkText("Magasinet Klima")).click();
    driver.findElement(By.linkText("Arrangementer")).click();
    {
      WebElement element = driver.findElement(By.linkText("Arrangementer"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".styles_menu__nfvg6")).click();
    driver.findElement(By.linkText("Ansatte")).click();
    driver.close();
  }
  @Test
  public void ciceroVrekspertise() {
    driver.get("https://cicero.oslo.no/no");
    driver.manage().window().setSize(new Dimension(1408, 1085));
    driver.findElement(By.cssSelector("div:nth-child(1) > .styles_large__6JIQO .styles_shortcutTile__pbJec:nth-child(1) .styles_title__vOtVv")).click();
    driver.findElement(By.cssSelector(".styles_searchBarWrapper__hx652 input")).click();
    driver.findElement(By.cssSelector(".styles_searchBarWrapper__hx652 input")).sendKeys("Arktis");
    driver.findElement(By.cssSelector(".styles_searchBarWrapper__hx652 .styles_submitBtn__sj98V")).click();
    driver.findElement(By.cssSelector("h3")).click();
    driver.findElement(By.cssSelector(".styles_oneColumn__c8URn:nth-child(1) .styles_image__KrnLv h3")).click();
    driver.close();
  }
}
